
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kotmich97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kotmich97/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-2-549763103163"
  bucket_path: "react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY