
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kotmich97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kotmich97/docker-react npm run test